#!/usr/bin/env python3
"""Tests for the ``datregrade.cube`` LUT toolkit.

The expected values come from two independent sources:

* algebraic identities that hold for any correct implementation (composing with
  the identity must be a no-op, blending at 0 must return the first LUT, ...);
* ``tests/data/golden_compose_preserve.cube``, a reference ``.cube`` generated by
  the third-party ``LUTify.py`` this module replaced. Those expectations are what
  pin the *conventions* -- file ordering, interpolation method, tie-breaking --
  since a reimplementation can be internally consistent yet disagree with the
  original on exactly those points.

Run with ``python -m pytest`` or directly as ``python tests/test_cube.py``.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from datregrade.cube import (  # noqa: E402
    Cube,
    CubeError,
    blend,
    compose,
    identity,
    interpolate,
    read_cube,
    resample,
    write_cube,
)

DATA = Path(__file__).resolve().parent / "data"


def grid(size: int) -> np.ndarray:
    """Return the ``(size, size, size, 3)`` input-coordinate grid for a LUT."""
    axis = np.arange(size, dtype=np.float64) / (size - 1)
    r, g, b = np.meshgrid(axis, axis, axis, indexing="ij")
    return np.stack([r, g, b], axis=-1)


class ReadWriteTests(unittest.TestCase):
    def test_round_trip_preserves_data(self) -> None:
        source = Cube(
            size=5,
            data=grid(5) ** 2,
            title="round trip",
            comments=["# a comment"],
        )
        path = Path("/tmp/_datregrade_roundtrip.cube")
        write_cube(path, source)
        loaded = read_cube(path)

        self.assertEqual(loaded.size, 5)
        self.assertEqual(loaded.title, "round trip")
        self.assertIn("# a comment", loaded.comments)
        np.testing.assert_allclose(loaded.data, source.data, atol=1e-9)

    def test_axis_order_matches_file_format(self) -> None:
        """A LUT whose output is its own input coordinate must round-trip.

        This is the check that catches a transposed axis order: reading a file
        back as an identity LUT only works if the r/g/b axes are laid out the
        same way the file format specifies.
        """
        path = DATA / "identity5.cube"
        loaded = read_cube(path)
        np.testing.assert_allclose(loaded.data, grid(5), atol=1e-9)

    def test_domain_is_normalized(self) -> None:
        path = Path("/tmp/_datregrade_domain.cube")
        path.write_text(
            "TITLE \"scaled\"\n"
            "DOMAIN_MIN 0 0 0\n"
            "DOMAIN_MAX 2 2 2\n"
            "LUT_3D_SIZE 2\n"
            "0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n2 2 2\n"
        )
        loaded = read_cube(path)
        self.assertEqual(loaded.data.min(), 0.0)
        self.assertEqual(loaded.data.max(), 1.0)

    def test_rejects_wrong_entry_count(self) -> None:
        path = Path("/tmp/_datregrade_bad.cube")
        path.write_text("LUT_3D_SIZE 3\n0 0 0\n")
        with self.assertRaises(CubeError):
            read_cube(path)

    def test_rejects_1d_lut(self) -> None:
        path = Path("/tmp/_datregrade_1d.cube")
        path.write_text("LUT_1D_SIZE 4\n0 0 0\n")
        with self.assertRaises(CubeError):
            read_cube(path)

    def test_rejects_missing_size(self) -> None:
        path = Path("/tmp/_datregrade_nosize.cube")
        path.write_text("TITLE \"x\"\n0 0 0\n")
        with self.assertRaises(CubeError):
            read_cube(path)


class InterpolationTests(unittest.TestCase):
    def test_identity_lut_is_exact_on_grid_points(self) -> None:
        lut = identity(5)
        coords = grid(5).reshape(-1, 3)
        np.testing.assert_allclose(interpolate(lut.data, coords), coords, atol=1e-12)

    def test_matches_known_composition(self) -> None:
        """swap_rb then halve_r gives (0.5*b, g, r) analytically."""
        result = compose(read_cube(DATA / "swap_rb.cube"), read_cube(DATA / "halve_r.cube"))
        r, g, b = (grid(5)[..., i] for i in range(3))
        expected = np.stack([0.5 * b, g, r], axis=-1)
        np.testing.assert_allclose(result.data, expected, atol=1e-9)

    def test_compose_matches_lutify_golden(self) -> None:
        golden = read_cube(DATA / "golden_compose_preserve.cube")
        result = compose(
            read_cube(DATA / "swap_rb.cube"),
            read_cube(DATA / "halve_r.cube"),
            preserve=True,
        )
        np.testing.assert_allclose(result.data, golden.data, atol=1e-6)

    def test_clamps_out_of_range_coordinates(self) -> None:
        lut = identity(5)
        below = interpolate(lut.data, np.array([-1.0, 0.5, 0.5]))
        above = interpolate(lut.data, np.array([2.0, 0.5, 0.5]))
        np.testing.assert_allclose(below, [0.0, 0.5, 0.5], atol=1e-12)
        np.testing.assert_allclose(above, [1.0, 0.5, 0.5], atol=1e-12)

    def test_nearest_rounds_ties_down(self) -> None:
        """LUTify's resize picks the lower grid point on an exact 0.5 tie."""
        lut = identity(3)
        # 0.25 is midway between grid points 0.0 and 0.5 of a 3-point LUT.
        result = interpolate(lut.data, np.array([0.25, 0.0, 0.0]), "nearest")
        np.testing.assert_allclose(result, [0.0, 0.0, 0.0], atol=1e-12)

    def test_single_and_batched_coords_agree(self) -> None:
        lut = read_cube(DATA / "swap_rb.cube")
        coords = np.array([[0.1, 0.5, 0.9], [0.9, 0.2, 0.3]])
        batched = interpolate(lut.data, coords)
        for i, coord in enumerate(coords):
            np.testing.assert_allclose(
                interpolate(lut.data, coord), batched[i], atol=1e-12
            )

    def test_rejects_unknown_method(self) -> None:
        with self.assertRaises(CubeError):
            interpolate(identity(3).data, np.array([0.5, 0.5, 0.5]), "cubic")


class ComposeTests(unittest.TestCase):
    def test_identity_is_neutral_on_both_sides(self) -> None:
        lut = read_cube(DATA / "swap_rb.cube")
        ident = identity(5)
        np.testing.assert_allclose(compose(ident, lut).data, lut.data, atol=1e-12)
        np.testing.assert_allclose(compose(lut, ident).data, lut.data, atol=1e-12)

    def test_composition_is_not_commutative(self) -> None:
        """Guards against silently swapping the two operands."""
        a = read_cube(DATA / "swap_rb.cube")
        b = read_cube(DATA / "halve_r.cube")
        self.assertFalse(np.allclose(compose(a, b).data, compose(b, a).data))

    def test_preserve_keeps_larger_size(self) -> None:
        big = read_cube(DATA / "swap_rb.cube")
        small = read_cube(DATA / "swap_rb_small.cube")
        self.assertEqual(compose(big, small, preserve=True).size, 5)
        self.assertEqual(compose(big, small, preserve=False).size, 3)
        self.assertEqual(compose(small, big, preserve=True).size, 5)
        self.assertEqual(compose(small, big, preserve=False).size, 3)

    def test_explicit_size_resamples_result(self) -> None:
        result = compose(
            read_cube(DATA / "swap_rb.cube"),
            read_cube(DATA / "halve_r.cube"),
            size=9,
        )
        self.assertEqual(result.size, 9)
        r, g, b = (grid(9)[..., i] for i in range(3))
        np.testing.assert_allclose(result.data, np.stack([0.5 * b, g, r], -1), atol=1e-9)

    def test_mixer_100_reduces_to_second_lut(self) -> None:
        """``mixer=100`` blends the first LUT fully to identity, so it yields the second.

        Verified against LUTify's ``--combine --mixer 100`` output.
        """
        a = read_cube(DATA / "swap_rb.cube")
        b = read_cube(DATA / "halve_r.cube")
        np.testing.assert_allclose(compose(a, b, mixer=100).data, b.data, atol=1e-12)

    def test_mixer_0_yields_source_lut(self) -> None:
        a = read_cube(DATA / "swap_rb.cube")
        b = read_cube(DATA / "halve_r.cube")
        np.testing.assert_allclose(compose(a, b, mixer=0).data, a.data, atol=1e-12)

    def test_mixer_out_of_range_rejected(self) -> None:
        a = read_cube(DATA / "swap_rb.cube")
        with self.assertRaises(CubeError):
            compose(a, a, mixer=101)


class BlendTests(unittest.TestCase):
    def test_endpoints_return_operands(self) -> None:
        a = read_cube(DATA / "swap_rb.cube")
        b = read_cube(DATA / "halve_r.cube")
        np.testing.assert_allclose(blend(a, b, 0.0).data, a.data, atol=1e-12)
        np.testing.assert_allclose(blend(a, b, 1.0).data, b.data, atol=1e-12)

    def test_midpoint_is_average(self) -> None:
        a = read_cube(DATA / "swap_rb.cube")
        b = read_cube(DATA / "halve_r.cube")
        np.testing.assert_allclose(
            blend(a, b, 0.5).data, (a.data + b.data) / 2.0, atol=1e-12
        )

    def test_size_mismatch_rejected(self) -> None:
        with self.assertRaises(CubeError):
            blend(read_cube(DATA / "swap_rb.cube"), read_cube(DATA / "swap_rb_small.cube"))


class ResampleTests(unittest.TestCase):
    def test_upsample_of_identity_stays_identity(self) -> None:
        result = resample(identity(3).data, 9)
        np.testing.assert_allclose(result, grid(9), atol=1e-9)

    def test_same_size_is_a_copy(self) -> None:
        original = identity(3).data
        result = resample(original, 3)
        np.testing.assert_allclose(result, original)
        self.assertIsNot(result, original)

    def test_size_below_two_rejected(self) -> None:
        with self.assertRaises(CubeError):
            resample(identity(3).data, 1)


class CubeValidationTests(unittest.TestCase):
    def test_shape_mismatch_rejected(self) -> None:
        with self.assertRaises(CubeError):
            Cube(size=3, data=np.zeros((3, 3, 3, 4)))

    def test_identity_size_below_two_rejected(self) -> None:
        with self.assertRaises(CubeError):
            identity(1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
